[package]
name = "tauri-plugin-websocket"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
rand = "0.8"
tauri = "1.0.0-rc.3"
futures-util = "0.3"
tokio = { version = "1.17", features = ["net", "sync"] }
tokio-tungstenite = { version = "0.17", features = ["native-tls"] }
